### ISSUE TITLE
TypeError: value.getTime is not a function. (In 'value.getTime()', 'value.getTime' is undefined)

### ISSUE THREAD

**Issue by dineshchaudhary923092** [gusparis/react-native-month-year-picker#43]
Giving TypeError in both android and ios after upgrading to 1.4.1. 

![Simulator Screen Shot - iPhone 11 - 2020-10-09 at 01 47 07](https://user-images.githubusercontent.com/17749863/95509266-e5042100-09d1-11eb-8ab3-aa7a212b48bc.png)
![WhatsApp Image 2020-10-09 at 01 47 36](https://user-images.githubusercontent.com/17749863/95509276-e7ff1180-09d1-11eb-9e01-f2ed5d4d9602.jpeg)

**Comment by gusparis** [comment]
Thank for using the library! It looks like you're sending an incorrect `Date` object. Can you share the code of your implementation?

**Comment by dineshchaudhary923092** [comment]
const [month, setMonth] = useState(moment(new Date()).format('MM YYYY'))

const onValueChange = (event, newDate) => {
        setShowPicker(false);
        const selectedMonth = newDate || month;
        setMonth(selectedMonth);
}

<MonthPicker
        onChange={onValueChange}
        value={month}
        minimumDate={new Date(2019, 12)}
        maximumDate={new Date(2025)}
        enableAutoDarkMode={true}
        outputFormat='MM YYYY'
        okButton="Select"
/>

**Comment by gusparis** [comment]
Ohh, I see. You are sending a moment object with outputFormat. I have deprecated that prop to decouple the component. Just send a Date object, and handle the logic on your side, when calling onChange using the line you have in the useState.

**Comment by dineshchaudhary923092** [comment]
Working Perfectly, Thank you very much
